trigger:
- master
- develop

pr:
- master
- develop
- feature/*

variables:
  sdk_version: 5.0.x
  sdk_support_preview: true
  dockerRepositoryRoot: sannel
  dockerTagBase: $(Build.SourceBranchName)-$(Build.BuildId)
  mainImageName: house.devices
  listenerImageName: house.devices.listener
  broadcasterImageName: house.devices.broadcaster
  imageTag: $(Build.SourceBranchName)-$(Build.BuildId)
  projectFolder: Sannel.House.Devices
  listenerProjectFolder: Sannel.House.Devices.Listener
  broadcasterProjectFolder: Sannel.House.Devices.Broadcaster
  tagVersion: 5.0
  tagCodeName: buster
  hasTests: true
  Major: 0
  Minor: 9

resources:
  repositories:
    - repository: templates
      type: github
      name: Sannel/Sannel.House.BuildScripts
      endpoint: Sannel

jobs:
- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm32
    archLong: arm32v7
    ridSuffix: arm
    qemuStatic: qemu-arm-static
    project: $(projectFolder)
    imageName: $(mainImageName)
    jobName: devices

- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm32
    archLong: arm32v7
    ridSuffix: arm
    qemuStatic: qemu-arm-static
    project: $(listenerProjectFolder)
    imageName: $(listenerImageName)
    jobName: deviceslistener

- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm32
    archLong: arm32v7
    ridSuffix: arm
    qemuStatic: qemu-arm-static
    project: $(broadcasterProjectFolder)
    imageName: $(broadcasterImageName)
    jobName: devicesbroadcaster

- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm64
    archLong: arm64v8
    project: $(projectFolder)
    imageName: $(mainImageName)
    jobName: devices

- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm64
    archLong: arm64v8
    project: $(listenerProjectFolder)
    imageName: $(listenerImageName)
    jobName: deviceslistener

- template: tasks/docker/linux-arm.yaml@templates
  parameters:
    arch: arm64
    archLong: arm64v8
    project: $(broadcasterProjectFolder)
    imageName: $(broadcasterImageName)
    jobName: devicesbroadcaster

- template: tasks/docker/linux-x64.yaml@templates
  parameters:
    project: $(projectFolder)
    imageName: $(mainImageName)
    jobName: devices

- template: tasks/docker/linux-x64.yaml@templates
  parameters:
    project: $(listenerProjectFolder)
    imageName: $(listenerImageName)
    jobName: deviceslistener

- template: tasks/docker/linux-x64.yaml@templates
  parameters:
    project: $(broadcasterProjectFolder)
    imageName: $(broadcasterImageName)
    jobName: devicesbroadcaster
