version: '2.4'

services:
  users:
    image: ${DOCKER_REGISTRY}sannelhouseusers

  devices:
    image: ${DOCKER_REGISTRY}sannelhousedevices:0.9-beta-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.Devices/Dockerfile
    depends_on:
      - users