version: '2.4'

services:
  users:
    volumes:
      - "./RunData/users/app_config:c:/app/app_config"
      - "./RunData/users/app_data:c:/app/app_data"

  devices:
    volumes:
      - "./src/Sannel.House.Devices/app_config:c:/app/app_config"
      - "./src/Sannel.House.Devices/app_data:c:/app/app_data"