version: '3.4'

services:
  devices.localtest.me:
    image: sannel/devices
    build:
      context: .
      dockerfile: src/Sannel.House.Devices/Dockerfile
    ports:
    - "8180:8080"
    volumes:
    - "./src/Sannel.House.Devices/app_config:/app/app_config"
    - "./src/Sannel.House.Devices/app_data:/app/app_data"

  mqtt.localtest.me:
    image: eclipse-mosquitto
    ports:
    - "8883:1883"

  users.localtest.me:
    image: sannel/house.users:beta
    ports:
    - "8181:8181"
    volumes:
    - "./RunData/users/app_config/appsettings.yml:/app/app_config/appsettings.yml"
    - "./RunData/users/app_data:/app/app_data/"
