version: '3.6'

services:
  devices:
    image: sannel/devices
    build:
      context: .
      dockerfile: src/Sannel.House.Devices/Dockerfile
    networks: 
      housenet:
        aliases:
          - "devices.localtest.me"
    ports:
      - "8183:8080"
    volumes:
    - "./src/Sannel.House.Devices/app_config:/app/app_config"
    - "./src/Sannel.House.Devices/app_data:/app/app_data"
    depends_on:
    - mqtt

  devices_listener:
    image: sannel/deviceslistener
    build:
      context: .
      dockerfile: src/Sannel.House.Devices.Listener/Dockerfile
    networks: 
      housenet:
        aliases:
          - "deviceslistener.localtest.me"
    volumes:
    - "./src/Sannel.House.Devices.Listener/app_config:/app/app_config"
    - "./src/Sannel.House.Devices/app_data:/app/app_data"
    depends_on:
    - mqtt

  devices_broadcaster:
    image: sannel/devicesbroadcaster
    build:
      context: .
      dockerfile: src/Sannel.House.Devices.Broadcaster/Dockerfile
    networks: 
    - housenet
    volumes:
    - "./src/Sannel.House.Devices.Broadcaster/app_config:/app/app_config"
    - "./src/Sannel.House.Devices/app_data:/app/app_data"
    depends_on:
    - mqtt
    - devices
    - devices_listener


  mqtt:
    image: eclipse-mosquitto
    ports:
    - "8883:1883"
    networks: 
      housenet:
        aliases:
          - "mqtt.localtest.me"


networks:
  housenet:
