version: '2.4'

services:
  users:
    image: ${DOCKER_REGISTRY}sannelhouseusers:beta
    networks: 
      housenet:
        aliases:
          - "users.house.dev.local"
    ports:
      - "443:443"

  tests:
    image: ${DOCKER_REGISTRY}sannelhousedevices:tests-${SANNEL_ARCH}
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: src/Sannel.House.Devices.Tests/Dockerfile
    networks:
      - housenet

  devices:
    image: ${DOCKER_REGISTRY}sannelhousedevices:${SANNEL_VERSION}-beta-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.Devices/Dockerfile
    networks:
      - housenet
    ports:
      - "8443:443"
    depends_on:
      - users

networks:
  housenet: