version: '2.4'

services:
  users:
    image: ${DOCKER_REGISTRY}house.users:beta
    networks: 
      housenet:
        aliases:
          - "users.house.dev.local"
        ipv4_address: '192.168.200.2'

  gateway:
    image: ${DOCKER_REGISTRY}house.gateway:beta
    volumes:
    - "./RunData/gateway:c:/app/app_config"
    networks: 
      housenet:
        aliases:
          - "users.house.dev.local"
        ipv4_address: '192.168.200.3'

  devices:
    image: ${DOCKER_REGISTRY}house.devices:alpha
    build:
      context: .
      dockerfile: src/Sannel.House.Devices/Dockerfile
    networks:
      housenet:
        aliases:
          - "devices.house.dev.local"
        ipv4_address: '192.168.200.4'
    depends_on:
      - users

networks:
  housenet:
    driver: nat
    ipam:
      driver: windows
      config:
        - subnet: '192.168.200.0/24'
          gateway: '192.168.200.1'
