---
Db:
  Provider: sqlite
  ConnectionString: Data Source=app_data/data.db
Authentication:
  Authority: https://test.us.auth0.com/
  Audience: "test audience"
  PermissionClaim: "permissions"
MQTT:
  Server: mqtt.localtest.me
  DefaultTopic: local/house/devices
  Port: 1883
  EnableSSL: False
Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
