---
Db:
  Provider: sqlite
  ConnectionString: Data Source=app_data/data.db
Authentication:
  AuthorityUrl: http://users.localtest.me:8181
  Schema: houseapi
  ApiName: houseapi
  ApiSecret: "@KiHRt7Uj0zssPlg2YvffMsUEd"
  DisableRequireHttpsMetadata: true
MQTT:
  Server: mqtt.localtest.me
  DefaultTopic: local/house/devices
  Port: 1883
  EnableSSL: False
#  Username: testuser
#  Password: Password
#  CertSubject: CN=test.com
#  CertIssuer: "CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US"
Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
