---
GlobalConfiguration:
  BaseUrl: http://192.168.200.3:8080
Authentication:
  AuthorityUrl: http://192.168.200.2:8080
  Schema: houseapi
  ApiName: houseapi
  ApiSecret: GatewayPassword
  DisableRequireHttpsMetadata: true
Cert:
  Install: false
  Crt: app_config/Sannel Software - Dev - CA.crt
Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8080
#    HTTPS:
#      Url: https://*:443
#      Certificate:
#        Path: app_config/house.dev.local.pfx
#        Password: "@Password1"
